// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbohMHRcJaNGUeM8Q39phE1WgIAstzhWE',
    appId: '1:138407541480:web:c76d6b9e5ac1ae2676a75d',
    messagingSenderId: '138407541480',
    projectId: 'students-ff391',
    authDomain: 'students-ff391.firebaseapp.com',
    storageBucket: 'students-ff391.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5Q5h0-Tdvpdx0-YiRxLPBRlokw8m1_o',
    appId: '1:138407541480:android:4b1c5a685a04e43a76a75d',
    messagingSenderId: '138407541480',
    projectId: 'students-ff391',
    storageBucket: 'students-ff391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVq_VJOPFJh-3xtfxGNVdmTGrgA1Uq8Rs',
    appId: '1:138407541480:ios:14a3030c6f6c20ca76a75d',
    messagingSenderId: '138407541480',
    projectId: 'students-ff391',
    storageBucket: 'students-ff391.firebasestorage.app',
    iosBundleId: 'com.example.fourstudents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVq_VJOPFJh-3xtfxGNVdmTGrgA1Uq8Rs',
    appId: '1:138407541480:ios:14a3030c6f6c20ca76a75d',
    messagingSenderId: '138407541480',
    projectId: 'students-ff391',
    storageBucket: 'students-ff391.firebasestorage.app',
    iosBundleId: 'com.example.fourstudents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbohMHRcJaNGUeM8Q39phE1WgIAstzhWE',
    appId: '1:138407541480:web:0d7e3c746af8da4776a75d',
    messagingSenderId: '138407541480',
    projectId: 'students-ff391',
    authDomain: 'students-ff391.firebaseapp.com',
    storageBucket: 'students-ff391.firebasestorage.app',
  );
}
